create table if not exists public.asset_transfers (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade,
  from_vessel_id bigint references public.vessels(id) on delete set null,
  to_vessel_id bigint references public.vessels(id) on delete set null,
  transferred_at timestamp with time zone default now(),
  transferred_by text,
  notes text
);

create index if not exists asset_transfers_asset_id_idx on public.asset_transfers (asset_id);
create index if not exists asset_transfers_to_vessel_id_idx on public.asset_transfers (to_vessel_id);
