create table if not exists public.asset_lifecycle_events (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade,
  event_type text not null,
  event_title text not null,
  remarks text,
  location text,
  performed_by text,
  event_timestamp timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.asset_documents (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade,
  document_type text not null,
  document_name text not null,
  document_url text not null,
  uploaded_at timestamptz default now()
);

create table if not exists public.asset_photos (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade,
  photo_name text not null,
  photo_url text not null,
  uploaded_at timestamptz default now()
);

create table if not exists public.asset_transfers (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete cascade,
  from_vessel_id bigint references public.vessels(id) on delete set null,
  to_vessel_id bigint references public.vessels(id) on delete set null,
  from_department text,
  to_department text,
  from_employee_id bigint references public.employees(id) on delete set null,
  to_employee_id bigint references public.employees(id) on delete set null,
  transferred_at timestamptz default now(),
  transferred_by text,
  notes text,
  transfer_type text default 'vessel'
);

create index if not exists idx_asset_lifecycle_asset_id on public.asset_lifecycle_events (asset_id);
create index if not exists idx_asset_documents_asset_id on public.asset_documents (asset_id);
create index if not exists idx_asset_photos_asset_id on public.asset_photos (asset_id);
create index if not exists idx_asset_transfers_asset_id on public.asset_transfers (asset_id);

alter table public.asset_lifecycle_events enable row level security;
alter table public.asset_documents enable row level security;
alter table public.asset_photos enable row level security;
alter table public.asset_transfers enable row level security;

create policy if not exists asset_lifecycle_events_select_all on public.asset_lifecycle_events for select using (true);
create policy if not exists asset_lifecycle_events_insert_all on public.asset_lifecycle_events for insert with check (true);
create policy if not exists asset_lifecycle_events_update_all on public.asset_lifecycle_events for update using (true) with check (true);
create policy if not exists asset_lifecycle_events_delete_all on public.asset_lifecycle_events for delete using (true);

create policy if not exists asset_documents_select_all on public.asset_documents for select using (true);
create policy if not exists asset_documents_insert_all on public.asset_documents for insert with check (true);
create policy if not exists asset_documents_update_all on public.asset_documents for update using (true) with check (true);
create policy if not exists asset_documents_delete_all on public.asset_documents for delete using (true);

create policy if not exists asset_photos_select_all on public.asset_photos for select using (true);
create policy if not exists asset_photos_insert_all on public.asset_photos for insert with check (true);
create policy if not exists asset_photos_update_all on public.asset_photos for update using (true) with check (true);
create policy if not exists asset_photos_delete_all on public.asset_photos for delete using (true);

create policy if not exists asset_transfers_select_all on public.asset_transfers for select using (true);
create policy if not exists asset_transfers_insert_all on public.asset_transfers for insert with check (true);
create policy if not exists asset_transfers_update_all on public.asset_transfers for update using (true) with check (true);
create policy if not exists asset_transfers_delete_all on public.asset_transfers for delete using (true);
