-- Enterprise RBAC schema for Phase 3
-- Creates user_roles and helper functions for workspace and vessel access.

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  role text not null,
  workspace text not null,
  vessel_id bigint null,
  department text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_roles_user_id_idx on public.user_roles (user_id);
create index if not exists user_roles_workspace_idx on public.user_roles (workspace);
create index if not exists user_roles_vessel_id_idx on public.user_roles (vessel_id);

alter table public.user_roles enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_roles_updated_at on public.user_roles;
create trigger trg_user_roles_updated_at
before update on public.user_roles
for each row
execute procedure public.set_updated_at();

create or replace function public.is_super_admin_role()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.is_active = true
      and lower(ur.role) in ('super_admin', 'super admin')
  );
$$;

create or replace function public.has_workspace_access(target_workspace text)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.is_active = true
      and (
        lower(ur.role) in ('super_admin', 'super admin')
        or lower(ur.workspace) = lower(target_workspace)
      )
  );
$$;

create or replace function public.has_vessel_access(target_vessel_id bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_roles ur
    where ur.user_id = auth.uid()
      and ur.is_active = true
      and (
        lower(ur.role) in ('super_admin', 'super admin')
        or (lower(ur.workspace) = 'vessel' and ur.vessel_id = target_vessel_id)
      )
  );
$$;

create or replace function public.can_access_office_data()
returns boolean
language sql
stable
as $$
  select public.has_workspace_access('office');
$$;

create or replace function public.can_access_fleet_data()
returns boolean
language sql
stable
as $$
  select public.has_workspace_access('fleet');
$$;

-- user_roles policies

drop policy if exists "user_roles_select_own" on public.user_roles;
create policy "user_roles_select_own"
  on public.user_roles
  for select
  using (user_id = auth.uid() or public.is_super_admin_role());

drop policy if exists "user_roles_insert_admin" on public.user_roles;
create policy "user_roles_insert_admin"
  on public.user_roles
  for insert
  with check (public.is_super_admin_role());

drop policy if exists "user_roles_update_admin" on public.user_roles;
create policy "user_roles_update_admin"
  on public.user_roles
  for update
  using (public.is_super_admin_role())
  with check (public.is_super_admin_role());

drop policy if exists "user_roles_delete_admin" on public.user_roles;
create policy "user_roles_delete_admin"
  on public.user_roles
  for delete
  using (public.is_super_admin_role());

-- Core application tables. Adjust if your physical schema uses different names.

drop policy if exists "assets_select_workspace" on public.assets;
create policy "assets_select_workspace"
  on public.assets
  for select
  using (
    public.can_access_office_data()
    or public.is_super_admin_role()
    or (vessel_id is not null and public.has_vessel_access(vessel_id))
  );

drop policy if exists "assets_write_workspace" on public.assets;
create policy "assets_write_workspace"
  on public.assets
  for insert
  with check (public.can_access_office_data() or public.is_super_admin_role());

drop policy if exists "assets_update_workspace" on public.assets;
create policy "assets_update_workspace"
  on public.assets
  for update
  using (public.can_access_office_data() or public.is_super_admin_role())
  with check (public.can_access_office_data() or public.is_super_admin_role());

drop policy if exists "employees_select_workspace" on public.employees;
create policy "employees_select_workspace"
  on public.employees
  for select
  using (public.can_access_office_data() or public.is_super_admin_role());

drop policy if exists "employees_write_workspace" on public.employees;
create policy "employees_write_workspace"
  on public.employees
  for insert
  with check (public.can_access_office_data() or public.is_super_admin_role());

drop policy if exists "tickets_select_workspace" on public.tickets;
create policy "tickets_select_workspace"
  on public.tickets
  for select
  using (
    public.can_access_office_data()
    or public.is_super_admin_role()
    or (vessel_id is not null and public.has_vessel_access(vessel_id))
  );

drop policy if exists "tickets_write_workspace" on public.tickets;
create policy "tickets_write_workspace"
  on public.tickets
  for insert
  with check (
    public.can_access_office_data()
    or public.is_super_admin_role()
    or (vessel_id is not null and public.has_vessel_access(vessel_id))
  );

drop policy if exists "asset_maintenance_select_workspace" on public.asset_maintenance;
create policy "asset_maintenance_select_workspace"
  on public.asset_maintenance
  for select
  using (
    public.can_access_office_data()
    or public.is_super_admin_role()
    or exists (
      select 1
      from public.assets a
      where a.id = asset_maintenance.asset_id
        and a.vessel_id is not null
        and public.has_vessel_access(a.vessel_id)
    )
  );

drop policy if exists "network_devices_select_workspace" on public.network_devices;
create policy "network_devices_select_workspace"
  on public.network_devices
  for select
  using (
    public.can_access_fleet_data()
    or public.is_super_admin_role()
    or (vessel_id is not null and public.has_vessel_access(vessel_id))
  );

drop policy if exists "vessel_it_checklists_select_workspace" on public.vessel_it_checklists;
create policy "vessel_it_checklists_select_workspace"
  on public.vessel_it_checklists
  for select
  using (public.is_super_admin_role() or (vessel_id is not null and public.has_vessel_access(vessel_id)));

drop policy if exists "vessels_select_workspace" on public.vessels;
create policy "vessels_select_workspace"
  on public.vessels
  for select
  using (public.can_access_fleet_data() or public.is_super_admin_role() or public.has_vessel_access(id));

drop policy if exists "audit_logs_select_workspace" on public.audit_logs;
create policy "audit_logs_select_workspace"
  on public.audit_logs
  for select
  using (public.can_access_office_data() or public.can_access_fleet_data() or public.is_super_admin_role());

drop policy if exists "audit_logs_insert_authenticated" on public.audit_logs;
create policy "audit_logs_insert_authenticated"
  on public.audit_logs
  for insert
  with check (auth.uid() is not null);

-- If your deployment still uses activity_logs, keep the same protections there too.
drop policy if exists "activity_logs_select_workspace" on public.activity_logs;
create policy "activity_logs_select_workspace"
  on public.activity_logs
  for select
  using (public.can_access_office_data() or public.can_access_fleet_data() or public.is_super_admin_role());

drop policy if exists "activity_logs_insert_authenticated" on public.activity_logs;
create policy "activity_logs_insert_authenticated"
  on public.activity_logs
  for insert
  with check (auth.uid() is not null);
