create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  location text,
  manager_employee_id bigint references public.employees(id) on delete set null,
  capacity_units numeric(14,2) default 0,
  status text default 'Active' check (status in ('Active', 'Maintenance', 'Inactive')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.warehouse_bins (
  id bigint generated by default as identity primary key,
  warehouse_id bigint not null references public.warehouses(id) on delete cascade,
  zone text,
  shelf text,
  bin_code text not null,
  capacity_units numeric(14,2) default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (warehouse_id, bin_code)
);

create table if not exists public.inventory_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  parent_id bigint references public.inventory_categories(id) on delete set null,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (name, parent_id)
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  asset_id bigint references public.assets(id) on delete set null,
  sku text not null unique,
  barcode text,
  qr_code text,
  item_name text not null,
  category text,
  brand text,
  model text,
  warehouse_id bigint references public.warehouses(id) on delete set null,
  bin_id bigint references public.warehouse_bins(id) on delete set null,
  quantity numeric(14,2) default 0 check (quantity >= 0),
  reserved_quantity numeric(14,2) default 0 check (reserved_quantity >= 0),
  available_quantity numeric(14,2) default 0 check (available_quantity >= 0),
  unit text default 'Nos',
  purchase_cost numeric(14,2) default 0,
  supplier_id bigint references public.asset_vendors(id) on delete set null,
  min_stock numeric(14,2) default 0,
  max_stock numeric(14,2) default 0,
  safety_stock numeric(14,2) default 0,
  reorder_level numeric(14,2) default 0,
  status text default 'Active',
  specifications text,
  images jsonb default '[]'::jsonb,
  documents jsonb default '[]'::jsonb,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
  movement_type text not null check (movement_type in ('Receive', 'Issue', 'Transfer', 'Return', 'Adjustment', 'Damage', 'Lost', 'Disposal')),
  quantity numeric(14,2) not null check (quantity > 0),
  warehouse_id bigint references public.warehouses(id) on delete set null,
  to_warehouse_id bigint references public.warehouses(id) on delete set null,
  reference_number text,
  status text default 'Posted',
  notes text,
  created_by text,
  created_at timestamptz default now()
);

create table if not exists public.stock_requests (
  id bigint generated by default as identity primary key,
  request_number text not null unique,
  request_type text,
  requester_employee_id bigint references public.employees(id) on delete set null,
  requester_department text,
  status text default 'Pending',
  priority text default 'Normal',
  required_date date,
  notes text,
  approved_by_employee_id bigint references public.employees(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.stock_transfers (
  id bigint generated by default as identity primary key,
  transfer_number text not null unique,
  inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
  from_warehouse_id bigint not null references public.warehouses(id) on delete restrict,
  to_warehouse_id bigint not null references public.warehouses(id) on delete restrict,
  quantity numeric(14,2) not null check (quantity > 0),
  status text default 'Pending',
  transfer_type text default 'Warehouse to Warehouse',
  requested_by_employee_id bigint references public.employees(id) on delete set null,
  approved_by_employee_id bigint references public.employees(id) on delete set null,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.purchase_receipts (
  id bigint generated by default as identity primary key,
  grn_number text not null unique,
  po_number text,
  supplier_id bigint references public.asset_vendors(id) on delete set null,
  receipt_date date,
  invoice_number text,
  invoice_url text,
  delivery_note_url text,
  status text default 'Pending',
  remarks text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.consumables (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint references public.inventory_items(id) on delete set null,
  item_name text not null,
  monthly_usage numeric(14,2) default 0,
  department_usage jsonb default '{}'::jsonb,
  forecast_next_month numeric(14,2) default 0,
  status text default 'Active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.inventory_audits (
  id bigint generated by default as identity primary key,
  audit_number text not null unique,
  warehouse_id bigint references public.warehouses(id) on delete set null,
  audit_date date,
  status text default 'Scheduled',
  variance_count integer default 0,
  missing_count integer default 0,
  damaged_count integer default 0,
  signature_name text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.cycle_counts (
  id bigint generated by default as identity primary key,
  count_number text not null unique,
  abc_class text default 'A',
  count_type text default 'Scheduled',
  scheduled_date date,
  status text default 'Scheduled',
  variance_value numeric(14,2) default 0,
  approved_by_employee_id bigint references public.employees(id) on delete set null,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.inventory_reports (
  id bigint generated by default as identity primary key,
  report_type text not null,
  filter_payload jsonb default '{}'::jsonb,
  generated_by text,
  generated_at timestamptz default now()
);

create table if not exists public.inventory_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text not null,
  value_type text default 'text',
  updated_at timestamptz default now()
);

create table if not exists public.inventory_activity_logs (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint references public.inventory_items(id) on delete cascade,
  action text not null,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_inventory_items_warehouse_id on public.inventory_items(warehouse_id);
create index if not exists idx_inventory_items_supplier_id on public.inventory_items(supplier_id);
create index if not exists idx_inventory_items_category on public.inventory_items(category);
create index if not exists idx_stock_movements_item_id on public.stock_movements(inventory_item_id);
create index if not exists idx_stock_movements_created_at on public.stock_movements(created_at);
create index if not exists idx_stock_requests_status on public.stock_requests(status);
create index if not exists idx_stock_transfers_status on public.stock_transfers(status);
create index if not exists idx_purchase_receipts_status on public.purchase_receipts(status);
create index if not exists idx_inventory_audits_status on public.inventory_audits(status);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.apply_stock_movement_to_item()
returns trigger
language plpgsql
as $$
begin
  if new.movement_type = 'Receive' or new.movement_type = 'Return' then
    update public.inventory_items
    set quantity = quantity + new.quantity,
        available_quantity = greatest(0, available_quantity + new.quantity),
        updated_at = now()
    where id = new.inventory_item_id;
  elsif new.movement_type in ('Issue', 'Damage', 'Lost', 'Disposal') then
    update public.inventory_items
    set quantity = greatest(0, quantity - new.quantity),
        available_quantity = greatest(0, available_quantity - new.quantity),
        updated_at = now()
    where id = new.inventory_item_id;
  elsif new.movement_type = 'Adjustment' then
    update public.inventory_items
    set quantity = greatest(0, quantity + new.quantity),
        available_quantity = greatest(0, available_quantity + new.quantity),
        updated_at = now()
    where id = new.inventory_item_id;
  end if;

  return new;
end;
$$;

create or replace function public.log_inventory_item_activity()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.inventory_activity_logs(inventory_item_id, action, payload)
    values (new.id, 'item_created', to_jsonb(new));
  elsif tg_op = 'UPDATE' then
    insert into public.inventory_activity_logs(inventory_item_id, action, payload)
    values (new.id, 'item_updated', jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new)));
  end if;
  return new;
end;
$$;

create or replace function public.ensure_inventory_item_for_asset(p_asset_id bigint)
returns bigint
language plpgsql
as $$
declare
  v_inventory_item_id bigint;
  v_asset record;
begin
  select id into v_inventory_item_id
  from public.inventory_items
  where asset_id = p_asset_id
  limit 1;

  if v_inventory_item_id is not null then
    return v_inventory_item_id;
  end if;

  select id, asset_tag, asset_name, category, brand, model, purchase_cost
  into v_asset
  from public.assets
  where id = p_asset_id;

  if v_asset.id is null then
    return null;
  end if;

  insert into public.inventory_items (
    asset_id,
    sku,
    item_name,
    category,
    brand,
    model,
    quantity,
    reserved_quantity,
    available_quantity,
    unit,
    purchase_cost,
    status
  ) values (
    v_asset.id,
    coalesce(nullif(v_asset.asset_tag, ''), concat('AST-', v_asset.id::text)),
    coalesce(nullif(v_asset.asset_name, ''), concat('Asset #', v_asset.id::text)),
    v_asset.category,
    v_asset.brand,
    v_asset.model,
    0,
    0,
    0,
    'Nos',
    coalesce(v_asset.purchase_cost, 0),
    'Active'
  )
  returning id into v_inventory_item_id;

  return v_inventory_item_id;
end;
$$;

create or replace function public.sync_inventory_on_asset_insert()
returns trigger
language plpgsql
as $$
declare
  v_item_id bigint;
begin
  v_item_id := public.ensure_inventory_item_for_asset(new.id);
  if v_item_id is not null then
    insert into public.stock_movements (
      inventory_item_id,
      movement_type,
      quantity,
      reference_number,
      status,
      notes,
      created_by
    ) values (
      v_item_id,
      'Receive',
      1,
      concat('ASSET-NEW-', new.id::text),
      'Posted',
      'Auto receive from asset registration',
      'asset_trigger'
    );
  end if;
  return new;
end;
$$;

create or replace function public.sync_inventory_on_assignment_insert()
returns trigger
language plpgsql
as $$
declare
  v_item_id bigint;
begin
  v_item_id := public.ensure_inventory_item_for_asset(new.asset_id);
  if v_item_id is not null then
    insert into public.stock_movements (
      inventory_item_id,
      movement_type,
      quantity,
      reference_number,
      status,
      notes,
      created_by
    ) values (
      v_item_id,
      'Issue',
      1,
      concat('ASN-', new.id::text),
      'Posted',
      'Auto issue from assignment record',
      'assignment_trigger'
    );
  end if;
  return new;
end;
$$;

create or replace function public.sync_inventory_on_asset_transfer_insert()
returns trigger
language plpgsql
as $$
declare
  v_item_id bigint;
begin
  v_item_id := public.ensure_inventory_item_for_asset(new.asset_id);
  if v_item_id is not null then
    insert into public.stock_movements (
      inventory_item_id,
      movement_type,
      quantity,
      reference_number,
      status,
      notes,
      created_by
    ) values (
      v_item_id,
      'Transfer',
      1,
      concat('TRN-', new.id::text),
      'Posted',
      'Auto transfer from asset transfer workflow',
      'asset_transfer_trigger'
    );
  end if;
  return new;
end;
$$;

create or replace function public.sync_inventory_on_asset_disposal_insert()
returns trigger
language plpgsql
as $$
declare
  v_item_id bigint;
begin
  v_item_id := public.ensure_inventory_item_for_asset(new.asset_id);
  if v_item_id is not null then
    insert into public.stock_movements (
      inventory_item_id,
      movement_type,
      quantity,
      reference_number,
      status,
      notes,
      created_by
    ) values (
      v_item_id,
      'Disposal',
      1,
      concat('DSP-', new.id::text),
      'Posted',
      'Auto disposal from asset disposal workflow',
      'asset_disposal_trigger'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_touch_warehouses on public.warehouses;
create trigger trg_touch_warehouses
before update on public.warehouses
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_warehouse_bins on public.warehouse_bins;
create trigger trg_touch_warehouse_bins
before update on public.warehouse_bins
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_inventory_categories on public.inventory_categories;
create trigger trg_touch_inventory_categories
before update on public.inventory_categories
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_inventory_items on public.inventory_items;
create trigger trg_touch_inventory_items
before update on public.inventory_items
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_stock_requests on public.stock_requests;
create trigger trg_touch_stock_requests
before update on public.stock_requests
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_stock_transfers on public.stock_transfers;
create trigger trg_touch_stock_transfers
before update on public.stock_transfers
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_purchase_receipts on public.purchase_receipts;
create trigger trg_touch_purchase_receipts
before update on public.purchase_receipts
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_consumables on public.consumables;
create trigger trg_touch_consumables
before update on public.consumables
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_inventory_audits on public.inventory_audits;
create trigger trg_touch_inventory_audits
before update on public.inventory_audits
for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_cycle_counts on public.cycle_counts;
create trigger trg_touch_cycle_counts
before update on public.cycle_counts
for each row execute function public.touch_updated_at();

drop trigger if exists trg_apply_stock_movement on public.stock_movements;
create trigger trg_apply_stock_movement
after insert on public.stock_movements
for each row execute function public.apply_stock_movement_to_item();

drop trigger if exists trg_log_inventory_item_activity on public.inventory_items;
create trigger trg_log_inventory_item_activity
after insert or update on public.inventory_items
for each row execute function public.log_inventory_item_activity();

drop trigger if exists trg_sync_inventory_on_asset_insert on public.assets;
create trigger trg_sync_inventory_on_asset_insert
after insert on public.assets
for each row execute function public.sync_inventory_on_asset_insert();

drop trigger if exists trg_sync_inventory_on_assignment_insert on public.assignment_records;
create trigger trg_sync_inventory_on_assignment_insert
after insert on public.assignment_records
for each row execute function public.sync_inventory_on_assignment_insert();

drop trigger if exists trg_sync_inventory_on_asset_transfer_insert on public.asset_transfers;
create trigger trg_sync_inventory_on_asset_transfer_insert
after insert on public.asset_transfers
for each row execute function public.sync_inventory_on_asset_transfer_insert();

drop trigger if exists trg_sync_inventory_on_asset_disposal_insert on public.asset_disposals;
create trigger trg_sync_inventory_on_asset_disposal_insert
after insert on public.asset_disposals
for each row execute function public.sync_inventory_on_asset_disposal_insert();

alter table public.warehouses enable row level security;
alter table public.warehouse_bins enable row level security;
alter table public.inventory_categories enable row level security;
alter table public.inventory_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.stock_requests enable row level security;
alter table public.stock_transfers enable row level security;
alter table public.purchase_receipts enable row level security;
alter table public.consumables enable row level security;
alter table public.inventory_audits enable row level security;
alter table public.cycle_counts enable row level security;
alter table public.inventory_reports enable row level security;
alter table public.inventory_settings enable row level security;
alter table public.inventory_activity_logs enable row level security;

create policy if not exists warehouses_select_all on public.warehouses for select using (true);
create policy if not exists warehouses_insert_all on public.warehouses for insert with check (true);
create policy if not exists warehouses_update_all on public.warehouses for update using (true) with check (true);
create policy if not exists warehouses_delete_all on public.warehouses for delete using (true);

create policy if not exists warehouse_bins_select_all on public.warehouse_bins for select using (true);
create policy if not exists warehouse_bins_insert_all on public.warehouse_bins for insert with check (true);
create policy if not exists warehouse_bins_update_all on public.warehouse_bins for update using (true) with check (true);
create policy if not exists warehouse_bins_delete_all on public.warehouse_bins for delete using (true);

create policy if not exists inventory_categories_select_all on public.inventory_categories for select using (true);
create policy if not exists inventory_categories_insert_all on public.inventory_categories for insert with check (true);
create policy if not exists inventory_categories_update_all on public.inventory_categories for update using (true) with check (true);
create policy if not exists inventory_categories_delete_all on public.inventory_categories for delete using (true);

create policy if not exists inventory_items_select_all on public.inventory_items for select using (true);
create policy if not exists inventory_items_insert_all on public.inventory_items for insert with check (true);
create policy if not exists inventory_items_update_all on public.inventory_items for update using (true) with check (true);
create policy if not exists inventory_items_delete_all on public.inventory_items for delete using (true);

create policy if not exists stock_movements_select_all on public.stock_movements for select using (true);
create policy if not exists stock_movements_insert_all on public.stock_movements for insert with check (true);
create policy if not exists stock_movements_update_all on public.stock_movements for update using (true) with check (true);
create policy if not exists stock_movements_delete_all on public.stock_movements for delete using (true);

create policy if not exists stock_requests_select_all on public.stock_requests for select using (true);
create policy if not exists stock_requests_insert_all on public.stock_requests for insert with check (true);
create policy if not exists stock_requests_update_all on public.stock_requests for update using (true) with check (true);
create policy if not exists stock_requests_delete_all on public.stock_requests for delete using (true);

create policy if not exists stock_transfers_select_all on public.stock_transfers for select using (true);
create policy if not exists stock_transfers_insert_all on public.stock_transfers for insert with check (true);
create policy if not exists stock_transfers_update_all on public.stock_transfers for update using (true) with check (true);
create policy if not exists stock_transfers_delete_all on public.stock_transfers for delete using (true);

create policy if not exists purchase_receipts_select_all on public.purchase_receipts for select using (true);
create policy if not exists purchase_receipts_insert_all on public.purchase_receipts for insert with check (true);
create policy if not exists purchase_receipts_update_all on public.purchase_receipts for update using (true) with check (true);
create policy if not exists purchase_receipts_delete_all on public.purchase_receipts for delete using (true);

create policy if not exists consumables_select_all on public.consumables for select using (true);
create policy if not exists consumables_insert_all on public.consumables for insert with check (true);
create policy if not exists consumables_update_all on public.consumables for update using (true) with check (true);
create policy if not exists consumables_delete_all on public.consumables for delete using (true);

create policy if not exists inventory_audits_select_all on public.inventory_audits for select using (true);
create policy if not exists inventory_audits_insert_all on public.inventory_audits for insert with check (true);
create policy if not exists inventory_audits_update_all on public.inventory_audits for update using (true) with check (true);
create policy if not exists inventory_audits_delete_all on public.inventory_audits for delete using (true);

create policy if not exists cycle_counts_select_all on public.cycle_counts for select using (true);
create policy if not exists cycle_counts_insert_all on public.cycle_counts for insert with check (true);
create policy if not exists cycle_counts_update_all on public.cycle_counts for update using (true) with check (true);
create policy if not exists cycle_counts_delete_all on public.cycle_counts for delete using (true);

create policy if not exists inventory_reports_select_all on public.inventory_reports for select using (true);
create policy if not exists inventory_reports_insert_all on public.inventory_reports for insert with check (true);
create policy if not exists inventory_reports_update_all on public.inventory_reports for update using (true) with check (true);
create policy if not exists inventory_reports_delete_all on public.inventory_reports for delete using (true);

create policy if not exists inventory_settings_select_all on public.inventory_settings for select using (true);
create policy if not exists inventory_settings_insert_all on public.inventory_settings for insert with check (true);
create policy if not exists inventory_settings_update_all on public.inventory_settings for update using (true) with check (true);
create policy if not exists inventory_settings_delete_all on public.inventory_settings for delete using (true);

create policy if not exists inventory_activity_logs_select_all on public.inventory_activity_logs for select using (true);
create policy if not exists inventory_activity_logs_insert_all on public.inventory_activity_logs for insert with check (true);
create policy if not exists inventory_activity_logs_update_all on public.inventory_activity_logs for update using (true) with check (true);
create policy if not exists inventory_activity_logs_delete_all on public.inventory_activity_logs for delete using (true);
