create table if not exists public.network_devices (
  id bigint generated by default as identity primary key,
  vessel_id bigint references public.vessels(id) on delete set null,
  device_name text not null,
  device_type text not null default 'Router',
  ip_address text not null,
  status text not null default 'Online',
  firmware text,
  last_seen timestamptz default now(),
  internet_speed_mbps numeric,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.network_alerts (
  id bigint generated by default as identity primary key,
  device_id bigint references public.network_devices(id) on delete set null,
  title text not null,
  message text,
  severity text not null default 'medium',
  created_at timestamptz default now(),
  resolved boolean default false
);

create index if not exists idx_network_devices_vessel_id on public.network_devices (vessel_id);
create index if not exists idx_network_devices_status on public.network_devices (status);
create index if not exists idx_network_alerts_device_id on public.network_alerts (device_id);
create index if not exists idx_network_alerts_created_at on public.network_alerts (created_at desc);

alter table public.network_devices enable row level security;
alter table public.network_alerts enable row level security;

create policy if not exists network_devices_select_all on public.network_devices
  for select using (true);
create policy if not exists network_devices_insert_all on public.network_devices
  for insert with check (true);
create policy if not exists network_devices_update_all on public.network_devices
  for update using (true) with check (true);
create policy if not exists network_devices_delete_all on public.network_devices
  for delete using (true);

create policy if not exists network_alerts_select_all on public.network_alerts
  for select using (true);
create policy if not exists network_alerts_insert_all on public.network_alerts
  for insert with check (true);
create policy if not exists network_alerts_update_all on public.network_alerts
  for update using (true) with check (true);
create policy if not exists network_alerts_delete_all on public.network_alerts
  for delete using (true);
