create table if not exists public.asset_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.asset_vendors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact_person text,
  email text,
  phone text,
  address text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.asset_purchase_orders (
  id bigint generated by default as identity primary key,
  po_number text not null unique,
  vendor_name text not null,
  purchase_date date,
  total_amount numeric(14,2),
  status text default 'Draft',
  invoice_url text,
  remarks text,
  created_by text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.asset_register_extensions (
  asset_id bigint primary key references public.assets(id) on delete cascade,
  vendor text,
  department text,
  location text,
  asset_condition text,
  remarks text,
  barcode_value text,
  invoice_url text,
  photo_url text,
  updated_at timestamptz default now()
);

create table if not exists public.asset_disposals (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.assets(id) on delete cascade,
  disposal_date date,
  method text,
  sale_value numeric(14,2),
  remarks text,
  disposed_by text,
  created_at timestamptz default now()
);

create index if not exists idx_asset_po_vendor_name on public.asset_purchase_orders(vendor_name);
create index if not exists idx_asset_disposals_asset_id on public.asset_disposals(asset_id);

alter table public.asset_categories enable row level security;
alter table public.asset_vendors enable row level security;
alter table public.asset_purchase_orders enable row level security;
alter table public.asset_register_extensions enable row level security;
alter table public.asset_disposals enable row level security;

create policy if not exists asset_categories_select_all on public.asset_categories for select using (true);
create policy if not exists asset_categories_insert_all on public.asset_categories for insert with check (true);
create policy if not exists asset_categories_update_all on public.asset_categories for update using (true) with check (true);
create policy if not exists asset_categories_delete_all on public.asset_categories for delete using (true);

create policy if not exists asset_vendors_select_all on public.asset_vendors for select using (true);
create policy if not exists asset_vendors_insert_all on public.asset_vendors for insert with check (true);
create policy if not exists asset_vendors_update_all on public.asset_vendors for update using (true) with check (true);
create policy if not exists asset_vendors_delete_all on public.asset_vendors for delete using (true);

create policy if not exists asset_purchase_orders_select_all on public.asset_purchase_orders for select using (true);
create policy if not exists asset_purchase_orders_insert_all on public.asset_purchase_orders for insert with check (true);
create policy if not exists asset_purchase_orders_update_all on public.asset_purchase_orders for update using (true) with check (true);
create policy if not exists asset_purchase_orders_delete_all on public.asset_purchase_orders for delete using (true);

create policy if not exists asset_register_extensions_select_all on public.asset_register_extensions for select using (true);
create policy if not exists asset_register_extensions_insert_all on public.asset_register_extensions for insert with check (true);
create policy if not exists asset_register_extensions_update_all on public.asset_register_extensions for update using (true) with check (true);
create policy if not exists asset_register_extensions_delete_all on public.asset_register_extensions for delete using (true);

create policy if not exists asset_disposals_select_all on public.asset_disposals for select using (true);
create policy if not exists asset_disposals_insert_all on public.asset_disposals for insert with check (true);
create policy if not exists asset_disposals_update_all on public.asset_disposals for update using (true) with check (true);
create policy if not exists asset_disposals_delete_all on public.asset_disposals for delete using (true);
