create table if not exists public.office_departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  manager_employee_id bigint references public.employees(id) on delete set null,
  location text,
  budget numeric(14,2) default 0,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.office_visitors (
  id bigint generated by default as identity primary key,
  visitor_name text not null,
  company text,
  phone text,
  email text,
  host_employee_id bigint references public.employees(id) on delete set null,
  host_department text,
  purpose text,
  vehicle_number text,
  photo_url text,
  id_proof_url text,
  badge_number text,
  visit_time timestamptz,
  expected_exit_time timestamptz,
  check_in_time timestamptz,
  check_out_time timestamptz,
  status text not null default 'Pending',
  is_blocked boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.office_attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('Present', 'Absent', 'Half Day', 'Leave')),
  check_in_time timestamptz,
  check_out_time timestamptz,
  late_by_minutes integer default 0,
  overtime_minutes integer default 0,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (employee_id, attendance_date)
);

create table if not exists public.office_leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  leave_type text not null check (leave_type in ('Casual', 'Sick', 'Earned', 'Maternity', 'Paternity', 'Unpaid')),
  start_date date not null,
  end_date date not null,
  total_days numeric(8,2) not null,
  reason text,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  approved_by_employee_id bigint references public.employees(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.office_performance_reviews (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  review_period text not null,
  kpi_score numeric(5,2),
  goals_score numeric(5,2),
  overall_rating numeric(4,2),
  comments text,
  reviewer_employee_id bigint references public.employees(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.office_training_records (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  course_name text not null,
  provider text,
  certification_name text,
  completion_date date,
  expiry_date date,
  status text default 'Planned' check (status in ('Planned', 'In Progress', 'Completed', 'Expired')),
  score numeric(5,2),
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.office_employee_documents (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  document_type text not null check (document_type in ('Passport', 'PAN', 'Aadhaar', 'Offer Letter', 'NDA', 'Certificate', 'Contract', 'Other')),
  document_name text not null,
  document_url text,
  issued_on date,
  expiry_date date,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_office_visitors_status on public.office_visitors (status);
create index if not exists idx_office_visitors_visit_time on public.office_visitors (visit_time);
create index if not exists idx_office_attendance_date on public.office_attendance (attendance_date);
create index if not exists idx_office_leave_requests_dates on public.office_leave_requests (start_date, end_date);
create index if not exists idx_office_training_expiry on public.office_training_records (expiry_date);
create index if not exists idx_office_employee_documents_expiry on public.office_employee_documents (expiry_date);

alter table public.office_departments enable row level security;
alter table public.office_visitors enable row level security;
alter table public.office_attendance enable row level security;
alter table public.office_leave_requests enable row level security;
alter table public.office_performance_reviews enable row level security;
alter table public.office_training_records enable row level security;
alter table public.office_employee_documents enable row level security;

drop policy if exists office_departments_all on public.office_departments;
create policy office_departments_all on public.office_departments for all using (true) with check (true);

drop policy if exists office_visitors_all on public.office_visitors;
create policy office_visitors_all on public.office_visitors for all using (true) with check (true);

drop policy if exists office_attendance_all on public.office_attendance;
create policy office_attendance_all on public.office_attendance for all using (true) with check (true);

drop policy if exists office_leave_requests_all on public.office_leave_requests;
create policy office_leave_requests_all on public.office_leave_requests for all using (true) with check (true);

drop policy if exists office_performance_reviews_all on public.office_performance_reviews;
create policy office_performance_reviews_all on public.office_performance_reviews for all using (true) with check (true);

drop policy if exists office_training_records_all on public.office_training_records;
create policy office_training_records_all on public.office_training_records for all using (true) with check (true);

drop policy if exists office_employee_documents_all on public.office_employee_documents;
create policy office_employee_documents_all on public.office_employee_documents for all using (true) with check (true);
