create table if not exists public.vessels (
  id bigint generated by default as identity primary key,
  vessel_name text not null,
  imo_number text not null,
  call_sign text,
  vessel_type text,
  flag text,
  owner text,
  manager text,
  fleet text,
  captain text,
  chief_engineer text,
  internet_provider text,
  satellite_provider text,
  starlink_enabled boolean default false,
  operating_region text,
  status text default 'Active',
  year_built integer,
  gross_tonnage numeric,
  last_it_inspection date,
  next_it_inspection date,
  remarks text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists vessels_status_idx on public.vessels (status);
create index if not exists vessels_fleet_idx on public.vessels (fleet);
create index if not exists vessels_captain_idx on public.vessels (captain);
