create table if not exists public.vessel_checklists (
  id bigint generated by default as identity primary key,
  vessel_id bigint references public.vessels(id) on delete cascade,
  checklist_type text not null,
  checklist_date date not null,
  status text not null default 'Completed',
  result text not null default 'Passed',
  remarks text,
  created_at timestamp with time zone default now()
);

create table if not exists public.vessel_checklist_items (
  id bigint generated by default as identity primary key,
  checklist_id bigint references public.vessel_checklists(id) on delete cascade,
  item_name text not null,
  status text not null default 'pass',
  remarks text,
  created_at timestamp with time zone default now()
);

create index if not exists vessel_checklists_vessel_id_idx on public.vessel_checklists (vessel_id);
create index if not exists vessel_checklists_date_idx on public.vessel_checklists (checklist_date);
